#!/bin/bash
cat >dist/cjs/package.json <<!EOF
{
    "type": "commonjs",
    "browser": {
        "./process/index.js": "./process/browser.js",
        "./cuid/fingerprint/index.js": "./cuid/fingerprint/browser.js"
    }
}
!EOF

cat >dist/esm/package.json <<!EOF
{
    "type": "module",
    "browser": {
        "./process/index.js": "./process/browser.js",
        "./cuid/fingerprint/index.js": "./cuid/fingerprint/browser.js"
    }
}
!EOF