#!/bin/bash
# Create CommonJS package.json
cat >dist/cjs/package.json <<!EOF
{
    "type": "commonjs",
    "browser": {
        "./process/index.js": "./process/browser.js",
        "./cuid/fingerprint/index.js": "./cuid/fingerprint/browser.js"
    }
}
!EOF
# Write typings to support Node16 module resolution 
cat >dist/cjs/index.d.ts <<!EOF
export * from '../../types';
!EOF
# Create ESM package.json
cat >dist/esm/package.json <<!EOF
{
    "type": "module",
    "browser": {
        "./process/index.js": "./process/browser.js",
        "./cuid/fingerprint/index.js": "./cuid/fingerprint/browser.js"
    }
}
!EOF
# Write typings to support Node16 module resolution 
cat >dist/esm/index.d.ts <<!EOF
export * from '../../types';
!EOF
